#ifndef TC_CONFIG_H
#define TC_CONFIG_H

#define TC_CONF_VERSION "0.4.0"

#define TC_CONF_INDENT_SIZE 2

#define TC_CONF_DEFAULT_TILE_SIZE 32

#define TC_CONF_DEFAULT_CACHE_LINE 64

#endif // TC_CONFIG_H
